language: node_js
node_js:
  - "10"
  - "12"
  - "13"
script: 'npm run coverage'
after_success: 'npm run coveralls'
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
